---
version: '3.2'

services:
  orders:
    build:
      context: ./orders
    ports:
      - 5000:5000
    depends_on:
      - redis
      - kafka
    networks:
      - test-microservices

  billings:
    build:
      context: ./billings
    ports:
      - 5001:5000
    depends_on:
      - redis
      - kafka
    networks:
      - test-microservices

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - ot-microservices

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_CREATE_TOPICS=orders:1:1,billings:1:1
    volumes:
      - kafka-data:/var/lib/kafka/data
      - kafka-logs:/var/lib/kafka/logs
    networks:
      - ot-microservices

networks:
  test-microservices:
    driver: bridge

volumes:
  redis-data:
  kafka-data:
  kafka-logs: